### ISSUE TITLE
Example please?

### ISSUE THREAD

**Issue by papiermache** [droyad/SqlAlias#3]
I have new asp.net core 3.1 app. Where does your code go? an example would be appreciated.
thx,Rick.

**Comment by droyad** [comment]
You pass it a connection string and it will replace the server. You then pass it to wherever it's needed. e.g.:

```
var aliasedConnectionString = Aliases.Map(myConnectionString)
```

**Comment by papiermache** [comment]
Got it, and got it working, thx!
