### ISSUE TITLE
Add support for .NET 5

### ISSUE THREAD

**Issue by mfas2410** [droyad/SqlAlias#7]
When compiling a .NET 5 project, the Aliases.Map() method doesn't process the connection string. Only .Net Core projects are supported.

I have put in a PR for supporting .NET 5 (and hopefully onwards) projects: https://github.com/droyad/SqlAlias/pull/6

**Comment by droyad** [comment]
I'll have a look today or tomorrow

**Comment by volikag** [comment]
Any plans to include this fix soon?

**Comment by droyad** [comment]
This is now done. .NET 5 reports as `.NET 5.0.0` while .NET 4.7.2 and earlier report as `.NET Framework x.y.z`.
